.TH topmdt 1 "version 1.1"
.SH NAME
topmdt \- Display client for a MDS, sorted by bandwith usage (open and get attribute for a file)
.SH SYNOPSIS
.B topmdt
.IR
.SH DESCRIPTION
.B topmdt
stat mdts counters and display client sorted by open/get attribute  usage
.bp
Need /etc/topmdt.conf to resolve nid to hostname
.SH OPTIONS
.TP
.BR \-n
number of client to print in the output
(10 is the default value)
.TP
.BR \-h
Print help
.TP
.BR \-v
Print version
.bp
.BR
.SH AUTHOR
Quentin Bouyer quentin.bouyer@gmail.com
